### ISSUE TITLE
Redo the end-user logic a bit

### ISSUE THREAD

**Issue by thwidge** [thwidge/pairing-bot#2]
After talking to folks about how they hope to use Pairing Bot, I've brainstormed this new bot-behavior accordingly:
* `subscribe` behavior unchanged
* `schedule` behavior unchanged, except:
  * `schedule no days` gives the user no recurring matches, but keeps them in the database
  * `schedule monday wednesday`, if issued when unsubscribed, subscribe and schedule for those days rather than erroring
  * `pair tomorrow` to sign up for a one-time match the next day
* `status` unchanged
* `unsubscribe` unchanged 
* `skip tomorrow` and `unskip tomorrow` unchanged

 I'm excited to work on this, but probably won't be able to focus on it much so movement may be slow. Feedback welcome!

**Comment by marenbeam** [comment]
I still like this framework, and I think pairing bot will behave this way after being re-written in python!

**Comment by thwidge** [comment]
I no longer like this framework! Closing, but willing to revisit in the future :)
