### ISSUE TITLE
Consistency in error handling

### ISSUE THREAD

**Issue by parsn1psoup** [thwidge/pairing-bot#26]
Right now, there's a couple of places where the code will panic on errors (which shouldn't happen in most cases), some cases where we just log and some cases where a request is aborted.
Make this consistent.
Reach out to @thwidge or me if you're interested in tackling this and have any questions!

**Comment by lutydlitatova** [comment]
Hi @thwidge @parsn1psoup! I'd like to learn a bit about Go and I thought trying to tackle this issue could be a good start. I've been reading about error handling in Go and I am now going through the code and identifying the places that should be modified.

**Comment by thwidge** [comment]
Awesome! I won't be able to help in a super hands-on way until august, but I'm happy to merge anything between now and then if you say it's ready!

**Comment by lutydlitatova** [comment]
The linked PR is ready for review. It's very small so I don't expect it to take a long time to go through.

**Comment by thwidge** [comment]
Thanks so much for working on this @lutydlitatova ! I'm glad to have more consistency here!

Since you've looked at this the most recently, do you think there's more places where we could increase consistency in error handling, or do you think it's pretty much as good as can be at the moment? If the latter, I'll go ahead and close this issue.

**Comment by lutydlitatova** [comment]
@thwidge The only part I'm not sure about is [this comment in `client.go`](https://github.com/thwidge/pairing-bot/blob/main/client.go#L52). Would you know if it is in scope of the issue?
Otherwise I believe this issue can be closed.

**Comment by thwidge** [comment]
I think not, since it's error handling for a specific function. Thanks again for your work on this! I'll close.
