### ISSUE TITLE
Send unsubscribe notification PM to people in the middle of their batch

### ISSUE THREAD

**Issue by marcin-morawski** [thwidge/pairing-bot#9]
# The problem
At the moment, every 6 weeks everyone is unsubscribed from the pairing bot. This ensures that we start with a clean slate at the start of each new batch. Otherwise, we'd need to track which subscribers are finishing their batch, which would be problematic (some people may want to pair even after the end of their batch, some people extend their batches etc.).

However, this is not clearly communicated to all the users. Currently, a message is sent on the first Wednesday of a batch to the `#397 Bridge` stream on Zulip. There is a lot of other noise in that stream, especially at the start of a batch, so this notification may go unnoticed.

# The solution
Automatically send a PM to notify users when they're unsubscribed, for whatever reason? Or send a blanket PM to `@currentlyatRC` at the start of the batch?

**Comment by thwidge** [comment]
Thanks for filing an issue @marcin-morawski ! Sorry I just now saw it -- for some reason I didn't get an email when this was filed.

Unfortunately the on/off-boarding process is currently manual. I just watch the calendar, and manually unsub everyone during the weekend after the last day of a batch. So there's no mechanism in pairing bot that's aware of the end of a batch.

Ah but there could be! This wouldn't be hard. There could be an end-of-batch endpoint that some outside cron triggers, or even if I was manually hitting the endpoint it would still be more automated than it is currently, and everyone could get a PM. Great idea!

I'll start working on this next week or the week after. Thank you for the input!

**Comment by marcin-morawski** [comment]
Thanks! I think that even just sending a PM automatically when you're unsubscribed (for whatever reason), would be useful. People may not realise that it's because of a new batch, but at least they'd know that they've been unsubbed.

**Comment by thwidge** [comment]
@marcin-morawski I've opened a PR to add this functionality if you'd like to have a look! I'll merge during the weekend following the current batch :)

https://github.com/thwidge/pairing-bot/pull/10

**Comment by marcin-morawski** [comment]
I don't know the codebase (and I don't know Go), but it looks good to me :)
